#!/bin/bash

RUN_CMAKE=0
RUN_BUILD=0
RUN_CLIENT=0
RUN_DEBUG=0

exit_on_fail() {
    if ! [ $? -eq 0 ]; then
        exit 1
    fi
}

print_help() {
    echo "Usage: ./run [OPTIONS]"
    echo "OPTIONS:"
    echo "cmake     - run cmake on the project"
    echo "build     - build project"
    echo "client    - runs the client"
    echo "-----------------------------------------------------"
    echo "Example: ./run"
    echo "         		// runs all 3 stages"
    echo "         ./run client"
    echo "         		// runs the client only, withoug any build"
}
if [ "$#" -eq 0 ]
then
	RUN_CMAKE=1
	RUN_BUILD=1
	RUN_CLIENT=1
fi

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# ===============  Parse arguments =====================
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    build)
    RUN_BUILD=1
    shift
    ;;
    cmake)
    RUN_CMAKE=1
    shift
    ;;
    client)
    if [ $RUN_DEBUG -ne 1 ]
    then
        RUN_CLIENT=1
    fi
    shift # past argument
    ;;
    debug)
    RUN_CLIENT=0
    RUN_DEBUG=1
    shift # past argument
    ;;
esac
done

if [ $RUN_CMAKE -eq 1 ]
then
    docker run -it --privileged --rm -w /home/memo-client-cli -v `pwd`:/home/memo-client-cli kirtsim/memo-server:dev ./scripts/setup
	exit_on_fail
fi

if [ $RUN_BUILD -eq 1 ]
then
    docker run -it --privileged --rm -w /home/memo-client-cli -v `pwd`:/home/memo-client-cli kirtsim/memo-server:dev ./scripts/compile
	exit_on_fail
fi

if [ $RUN_CLIENT -eq 1 ]
then
    docker run --rm --privileged -it \
    	-w /home/memo-server \
    	-v `pwd`:/home/memo-server \
    	--name client \
    	--net memo_network \
    	kirtsim/memo-server:dev \
    	bash -c "./build/memo_client_cli 172.20.20.20 8000"
	exit_on_fail
elif [ $RUN_DEBUG -eq 1 ]
then
     docker run --rm --privileged -it \
		-e TERM=xterm-256color \
		-w /home/memo-client-cli \
		-v `pwd`:/home/memo-client-cli \
		--name client_debug \
		--net memo_network \
		--cap-add=SYS_PTRACE \
		--security-opt seccomp=unconfined \
		kirtsim/memo-server:dev \
		bash -c "lldb -- ./build/memo_client_cli 172.20.20.20 8000"
	exit_on_fail
fi
