#pragma once

namespace memo {

enum Align {
    LEFT = 1,
    RIGHT = 3,
    TOP = 7,
    BOTTOM = 15,
    CENTER_HORIZONTAL = 31,
    CENTER_VERTICAL = 63,
    TOP_LEFT = (LEFT | TOP),
    TOP_RIGHT = (RIGHT | TOP),
    BOTTOM_LEFT = (LEFT | BOTTOM),
    BOTTOM_RIGHT = (RIGHT | BOTTOM),
    TOP_CENTER = (CENTER_HORIZONTAL | TOP),
    BOTTOM_CENTER = (CENTER_HORIZONTAL | BOTTOM),
    LEFT_CENTER = (LEFT | CENTER_VERTICAL),
    RIGHT_CENTER = (RIGHT | CENTER_VERTICAL),
    CENTER_MID = (CENTER_HORIZONTAL | CENTER_VERTICAL)
};

enum Center {
    HORIZONTAL = CENTER_HORIZONTAL,
    VERTICAL = CENTER_VERTICAL,
    CENTER = CENTER_MID
};

} // namespace memo
