#!/bin/bash

# Variables
BUILD_DIR="./build"
PROJECT_PATH=$(pwd)
EXECUTABLE="memo_client_cli"
CLIENT_ARGS="172.20.20.20 8000"

exit_on_fail() {
    if ! [ $? -eq 0 ]; then
        exit 1
    fi
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# ===============  COMPILATION/BUILD/MAKE =====================
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
cd $BUILD_DIR
exit_on_fail

echo "++ Building project"
echo "*******************************"
make -j4
exit_on_fail
echo "*******************************"
echo "++ Build successfull"
echo ""

rm $PROJECT_PATH/log/*.log
